### ISSUE TITLE
About mono_dataset.py

### ISSUE THREAD

**Issue by water221** [fcntes/IndoorDepth#5]
`Training model named:
   mdp
Models and tensorboard events files are saved to:
   /home/usst/zts/IndoorDepth/tmp
Training is using:
   cuda
/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Using split:
   nyu
There are 46848 training items and 1000 validation items

Training
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer.train()
  File "/home/usst/zts/IndoorDepth/trainer.py", line 185, in train
    self.run_epoch()
  File "/home/usst/zts/IndoorDepth/trainer.py", line 199, in run_epoch
    for batch_idx, inputs in enumerate(self.train_loader):
  File "/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/usst/miniconda3/envs/zts_IndoorDepth/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/usst/zts/IndoorDepth/datasets/mono_dataset.py", line 271, in __getitem__
    self.preprocess(inputs, color_aug)
  File "/home/usst/zts/IndoorDepth/datasets/mono_dataset.py", line 135, in preprocess
    inputs[(n + "_aug", im, i)] = self.to_tensor(color_aug(f))
TypeError: 'tuple' object is not callable`
Hello, I run the train.py file after preprocessing the dataset, but the above error occurs, saying that color_aug is a tuple in the mono_dataset.py file, not a function, and cannot be called. Do you know what to do?

**Comment by fcntes** [comment]
This issue may be caused by different torchvision versions. It can be fixed by modifying line 253 in our mono_dataset.py file. Modify it to the following code:
`color_aug = transforms.ColorJitter(`
