### ISSUE TITLE
some questions about training 、 extraction of superpixels and line segments

### ISSUE THREAD

**Issue by mrwangxinqwe** [fcntes/IndoorDepth#7]
I could not train properly. I used opencv-python3.4.0.14 to Extract the superpixels and line segments, but the problem still occurred.

Training model named:
   mdp
Models and tensorboard events files are saved to:
   D:\IndoorDepth-main\tmp
Training is using:
   cuda
Using split:
   nyu
There are 46848 training items and 1000 validation items

Traceback (most recent call last):
    trainer.train()
  File "D:\IndoorDepth-main\trainer.py", line 181, in train
    self.val()
  File "D:\IndoorDepth-main\trainer.py", line 497, in val
    outputs, losses = self.process_batch(inputs)
  File "D:\IndoorDepth-main\trainer.py", line 250, in process_batch
    losses = self.compute_losses(inputs, outputs)
    plane_loss = get_plane_loss(inputs[("plane_keysets", 0, scale)], norm_point3D)
KeyError: ('plane_keysets', 0, 0)

It doesn't seem to be doing much when I perform extraction of superpixels and line segments.At the same time, opencv_python is no longer available online for a version lower than 3.4.0.14.

when I perform extraction of superpixels and line segments,the terminal information is as follows:
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]

Do you have any ideas about it?

**Comment by mrwangxinqwe** [comment]
And I deployed this model on Windows.

**Comment by fcntes** [comment]
> I could not train properly. I used opencv-python3.4.0.14 to Extract the superpixels and line segments, but the problem still occurred.
> 
> Training model named: mdp Models and tensorboard events files are saved to: D:\IndoorDepth-main\tmp Training is using: cuda Using split: nyu There are 46848 training items and 1000 validation items
> 
> Traceback (most recent call last): trainer.train() File "D:\IndoorDepth-main\trainer.py", line 181, in train self.val() File "D:\IndoorDepth-main\trainer.py", line 497, in val outputs, losses = self.process_batch(inputs) File "D:\IndoorDepth-main\trainer.py", line 250, in process_batch losses = self.compute_losses(inputs, outputs) plane_loss = get_plane_loss(inputs[("plane_keysets", 0, scale)], norm_point3D) KeyError: ('plane_keysets', 0, 0)
> 
> It doesn't seem to be doing much when I perform extraction of superpixels and line segments.At the same time, opencv_python is no longer available online for a version lower than 3.4.0.14.
> 
> when I perform extraction of superpixels and line segments,the terminal information is as follows: 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s] 0it [00:00, ?it/s]
> 
> Do you have any ideas about it?

In addition to the 3.1.0.4 version of opencv in our readme file, we've also tried the version 3.3.1.11, which also worked. These kinds of problems are usually caused by the version of opencv, and you need to be careful to match it with your other libraries when installing. You can try a few more versions of opencv below 3.4.6.

**Comment by mrwangxinqwe** [comment]
Thank you for your reply. If possible, could you please provide the Opencv-Python file you use? For example, 3.3.1.11. I can't find an Opencv-Python version lower than 3.4.0.12 on the website or anywhere else, thank you very much. @fcntes
